###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID smartlab6.calicut.nielit.in)
#  Generated on:      Thu Aug  6 12:28:52 2026
#  Design:            top
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins were identified as implicit sinks
# The following pins are design outputs carrying SDC clocks
# These pins are ignore skew pins
set_ccopt_property sink_type -pin o_bram_clka ignore
set_ccopt_property sink_type_reasons -pin o_bram_clka {implicit design_io}
set_ccopt_property sink_type -pin o_bram_clkb ignore
set_ccopt_property sink_type_reasons -pin o_bram_clkb {implicit design_io}
set_ccopt_property sink_type -pin o_top_xclk ignore
set_ccopt_property sink_type_reasons -pin o_top_xclk {implicit design_io}

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin i_top_clk true
set_ccopt_property cts_is_sdc_clock_root -pin i_top_pclk true
set_ccopt_property cts_is_sdc_clock_root -pin w_clk25m true

# Clocks present at pin w_clk25m
#   w_clk25m (period 40.000ns) in timing_config CM_FUNC([../syn/sweep/E4/top_synth.sdc])
create_ccopt_clock_tree -name w_clk25m -source w_clk25m -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner DC_SS -early -clock_tree w_clk25m 5.000
set_ccopt_property target_max_trans_sdc -delay_corner DC_SS -late -clock_tree w_clk25m 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_SS -early -clock_tree w_clk25m 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_FF -early -clock_tree w_clk25m 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_SS -late -clock_tree w_clk25m 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_FF -late -clock_tree w_clk25m 5.000
# Clock period setting for source pin of w_clk25m
set_ccopt_property clock_period -pin w_clk25m 40

# Clocks present at pin i_top_pclk
#   i_top_pclk (period 40.000ns) in timing_config CM_FUNC([../syn/sweep/E4/top_synth.sdc])
create_ccopt_clock_tree -name i_top_pclk -source i_top_pclk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner DC_SS -early -clock_tree i_top_pclk 5.000
set_ccopt_property target_max_trans_sdc -delay_corner DC_SS -late -clock_tree i_top_pclk 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_SS -early -clock_tree i_top_pclk 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_FF -early -clock_tree i_top_pclk 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_SS -late -clock_tree i_top_pclk 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_FF -late -clock_tree i_top_pclk 5.000
# Clock period setting for source pin of i_top_pclk
set_ccopt_property clock_period -pin i_top_pclk 40

# Clocks present at pin i_top_clk
#   i_top_clk (period 20.000ns) in timing_config CM_FUNC([../syn/sweep/E4/top_synth.sdc])
create_ccopt_clock_tree -name i_top_clk -source i_top_clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner DC_SS -early -clock_tree i_top_clk 5.000
set_ccopt_property target_max_trans_sdc -delay_corner DC_SS -late -clock_tree i_top_clk 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_SS -early -clock_tree i_top_clk 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_FF -early -clock_tree i_top_clk 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_SS -late -clock_tree i_top_clk 5.000
set_ccopt_property source_output_max_trans -delay_corner DC_FF -late -clock_tree i_top_clk 5.000
# Clock period setting for source pin of i_top_clk
set_ccopt_property clock_period -pin i_top_clk 20

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:i_top_clk in timing_config:CM_FUNC (sdc ../syn/sweep/E4/top_synth.sdc)
create_ccopt_skew_group -name i_top_clk/CM_FUNC -sources i_top_clk -auto_sinks
set_ccopt_property include_source_latency -skew_group i_top_clk/CM_FUNC true
set_ccopt_property extracted_from_clock_name -skew_group i_top_clk/CM_FUNC i_top_clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group i_top_clk/CM_FUNC CM_FUNC
set_ccopt_property extracted_from_delay_corners -skew_group i_top_clk/CM_FUNC {DC_SS DC_FF}

# Skew group to balance non generated clock:i_top_pclk in timing_config:CM_FUNC (sdc ../syn/sweep/E4/top_synth.sdc)
create_ccopt_skew_group -name i_top_pclk/CM_FUNC -sources i_top_pclk -auto_sinks
set_ccopt_property include_source_latency -skew_group i_top_pclk/CM_FUNC true
set_ccopt_property extracted_from_clock_name -skew_group i_top_pclk/CM_FUNC i_top_pclk
set_ccopt_property extracted_from_constraint_mode_name -skew_group i_top_pclk/CM_FUNC CM_FUNC
set_ccopt_property extracted_from_delay_corners -skew_group i_top_pclk/CM_FUNC {DC_SS DC_FF}

# Skew group to balance non generated clock:w_clk25m in timing_config:CM_FUNC (sdc ../syn/sweep/E4/top_synth.sdc)
create_ccopt_skew_group -name w_clk25m/CM_FUNC -sources w_clk25m -auto_sinks
set_ccopt_property include_source_latency -skew_group w_clk25m/CM_FUNC true
set_ccopt_property extracted_from_clock_name -skew_group w_clk25m/CM_FUNC w_clk25m
set_ccopt_property extracted_from_constraint_mode_name -skew_group w_clk25m/CM_FUNC CM_FUNC
set_ccopt_property extracted_from_delay_corners -skew_group w_clk25m/CM_FUNC {DC_SS DC_FF}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

