# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Thu Aug 06 10:30:46 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design top

create_clock -name "i_top_pclk" -period 40.0 -waveform {0.0 20.0} [get_ports i_top_pclk]
create_clock -name "w_clk25m" -period 40.0 -waveform {0.0 20.0} [get_ports w_clk25m]
create_clock -name "i_top_clk" -period 25.0 -waveform {0.0 12.5} [get_ports i_top_clk]
set_clock_transition 0.1 [get_clocks i_top_pclk]
set_clock_transition 0.1 [get_clocks w_clk25m]
set_clock_transition 0.1 [get_clocks i_top_clk]
set_load -pin_load 0.136 [get_ports o_top_cam_done]
set_load -pin_load 0.136 [get_ports o_top_reset]
set_load -pin_load 0.136 [get_ports o_top_pwdn]
set_load -pin_load 0.136 [get_ports o_top_xclk]
set_load -pin_load 0.136 [get_ports o_top_sda_out]
set_load -pin_load 0.136 [get_ports o_top_sda_oe]
set_load -pin_load 0.136 [get_ports o_top_sioc]
set_load -pin_load 0.136 [get_ports {o_top_vga_red[3]}]
set_load -pin_load 0.136 [get_ports {o_top_vga_red[2]}]
set_load -pin_load 0.136 [get_ports {o_top_vga_red[1]}]
set_load -pin_load 0.136 [get_ports {o_top_vga_red[0]}]
set_load -pin_load 0.136 [get_ports {o_top_vga_green[3]}]
set_load -pin_load 0.136 [get_ports {o_top_vga_green[2]}]
set_load -pin_load 0.136 [get_ports {o_top_vga_green[1]}]
set_load -pin_load 0.136 [get_ports {o_top_vga_green[0]}]
set_load -pin_load 0.136 [get_ports {o_top_vga_blue[3]}]
set_load -pin_load 0.136 [get_ports {o_top_vga_blue[2]}]
set_load -pin_load 0.136 [get_ports {o_top_vga_blue[1]}]
set_load -pin_load 0.136 [get_ports {o_top_vga_blue[0]}]
set_load -pin_load 0.136 [get_ports o_top_vga_vsync]
set_load -pin_load 0.136 [get_ports o_top_vga_hsync]
set_load -pin_load 0.136 [get_ports o_bram_clka]
set_load -pin_load 0.136 [get_ports o_bram_ena]
set_load -pin_load 0.136 [get_ports o_bram_wea]
set_load -pin_load 0.136 [get_ports {o_bram_addra[18]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[17]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[16]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[15]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[14]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[13]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[12]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[11]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[10]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[9]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[8]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[7]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[6]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[5]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[4]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[3]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[2]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[1]}]
set_load -pin_load 0.136 [get_ports {o_bram_addra[0]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[11]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[10]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[9]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[8]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[7]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[6]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[5]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[4]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[3]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[2]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[1]}]
set_load -pin_load 0.136 [get_ports {o_bram_dina[0]}]
set_load -pin_load 0.136 [get_ports o_bram_clkb]
set_load -pin_load 0.136 [get_ports o_bram_enb]
set_load -pin_load 0.136 [get_ports o_bram_web]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[18]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[17]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[16]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[15]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[14]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[13]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[12]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[11]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[10]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[9]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[8]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[7]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[6]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[5]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[4]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[3]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[2]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[1]}]
set_load -pin_load 0.136 [get_ports {o_bram_addrb[0]}]
set_false_path -from [get_ports i_top_rst]
set_clock_groups -name "CG_ASYNC_DOMAINS" -asynchronous -group [get_clocks i_top_clk] -group [get_clocks i_top_pclk] -group [get_clocks w_clk25m]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports i_top_rst]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports i_top_cam_start]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {i_top_pix_byte[7]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {i_top_pix_byte[6]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {i_top_pix_byte[5]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {i_top_pix_byte[4]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {i_top_pix_byte[3]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {i_top_pix_byte[2]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {i_top_pix_byte[1]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {i_top_pix_byte[0]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports i_top_pix_vsync]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports i_top_pix_href]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports i_top_sda_in]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports i_top_rst]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports i_top_cam_start]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {i_top_pix_byte[7]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {i_top_pix_byte[6]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {i_top_pix_byte[5]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {i_top_pix_byte[4]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {i_top_pix_byte[3]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {i_top_pix_byte[2]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {i_top_pix_byte[1]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {i_top_pix_byte[0]}]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports i_top_pix_vsync]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports i_top_pix_href]
set_input_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports i_top_sda_in]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports o_top_cam_done]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports o_top_reset]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports o_top_pwdn]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports o_top_xclk]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports o_top_sda_out]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports o_top_sda_oe]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports o_top_sioc]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_red[3]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_red[2]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_red[1]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_red[0]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_green[3]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_green[2]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_green[1]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_green[0]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_blue[3]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_blue[2]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_blue[1]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports {o_top_vga_blue[0]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports o_top_vga_vsync]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -max 4.0 [get_ports o_top_vga_hsync]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports o_top_cam_done]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports o_top_reset]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports o_top_pwdn]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports o_top_xclk]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports o_top_sda_out]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports o_top_sda_oe]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports o_top_sioc]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_red[3]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_red[2]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_red[1]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_red[0]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_green[3]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_green[2]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_green[1]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_green[0]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_blue[3]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_blue[2]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_blue[1]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports {o_top_vga_blue[0]}]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports o_top_vga_vsync]
set_output_delay -clock [get_clocks i_top_clk] -add_delay -min 0.5 [get_ports o_top_vga_hsync]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports o_bram_clka]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports o_bram_ena]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports o_bram_wea]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[18]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[17]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[16]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[15]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[14]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[13]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[12]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[11]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[10]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[9]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[8]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[7]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[6]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[5]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[4]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[3]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[2]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[1]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_addra[0]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[11]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[10]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[9]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[8]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[7]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[6]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[5]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[4]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[3]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[2]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[1]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -max 4.0 [get_ports {o_bram_dina[0]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports o_bram_clka]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports o_bram_ena]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports o_bram_wea]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[18]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[17]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[16]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[15]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[14]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[13]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[12]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[11]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[10]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[9]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[8]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[7]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[6]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[5]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[4]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[3]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[2]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[1]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_addra[0]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[11]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[10]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[9]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[8]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[7]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[6]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[5]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[4]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[3]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[2]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[1]}]
set_output_delay -clock [get_clocks i_top_pclk] -add_delay -min 0.5 [get_ports {o_bram_dina[0]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports o_bram_clkb]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports o_bram_enb]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports o_bram_web]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[18]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[17]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[16]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[15]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[14]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[13]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[12]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[11]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[10]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[9]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[8]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[7]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[6]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[5]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[4]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[3]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[2]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[1]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {o_bram_addrb[0]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports o_bram_clkb]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports o_bram_enb]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports o_bram_web]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[18]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[17]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[16]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[15]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[14]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[13]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[12]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[11]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[10]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[9]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[8]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[7]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[6]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[5]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[4]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[3]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[2]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[1]}]
set_output_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {o_bram_addrb[0]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[11]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[10]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[9]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[8]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[7]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[6]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[5]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[4]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[3]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[2]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[1]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -max 4.0 [get_ports {i_bram_doutb[0]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[11]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[10]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[9]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[8]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[7]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[6]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[5]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[4]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[3]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[2]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[1]}]
set_input_delay -clock [get_clocks w_clk25m] -add_delay -min 0.5 [get_ports {i_bram_doutb[0]}]
set_max_fanout 16.000 [current_design]
set_max_transition 1.0 [current_design]
set_input_transition 0.15 [get_ports i_top_clk]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports i_top_rst]
set_input_transition 0.15 [get_ports w_clk25m]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports i_top_cam_start]
set_input_transition 0.15 [get_ports i_top_pclk]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_top_pix_byte[7]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_top_pix_byte[6]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_top_pix_byte[5]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_top_pix_byte[4]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_top_pix_byte[3]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_top_pix_byte[2]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_top_pix_byte[1]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_top_pix_byte[0]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports i_top_pix_vsync]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports i_top_pix_href]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports i_top_sda_in]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[11]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[10]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[9]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[8]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[7]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[6]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[5]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[4]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[3]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[2]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[1]}]
set_driving_cell -lib_cell INVR04 -library ss_125_2p45 -pin "OUT1" [get_ports {i_bram_doutb[0]}]
set_clock_uncertainty -setup 0.1 [get_clocks i_top_pclk]
set_clock_uncertainty -hold 0.05 [get_clocks i_top_pclk]
set_clock_uncertainty -setup 0.1 [get_clocks w_clk25m]
set_clock_uncertainty -hold 0.05 [get_clocks w_clk25m]
set_clock_uncertainty -setup 0.1 [get_clocks i_top_clk]
set_clock_uncertainty -hold 0.05 [get_clocks i_top_clk]
