
//input ports
add mapped point i_top_clk i_top_clk -type PI PI
add mapped point i_top_rst i_top_rst -type PI PI
add mapped point w_clk25m w_clk25m -type PI PI
add mapped point i_top_cam_start i_top_cam_start -type PI PI
add mapped point i_top_pclk i_top_pclk -type PI PI
add mapped point i_top_pix_byte[7] i_top_pix_byte[7] -type PI PI
add mapped point i_top_pix_byte[6] i_top_pix_byte[6] -type PI PI
add mapped point i_top_pix_byte[5] i_top_pix_byte[5] -type PI PI
add mapped point i_top_pix_byte[4] i_top_pix_byte[4] -type PI PI
add mapped point i_top_pix_byte[3] i_top_pix_byte[3] -type PI PI
add mapped point i_top_pix_byte[2] i_top_pix_byte[2] -type PI PI
add mapped point i_top_pix_byte[1] i_top_pix_byte[1] -type PI PI
add mapped point i_top_pix_byte[0] i_top_pix_byte[0] -type PI PI
add mapped point i_top_pix_vsync i_top_pix_vsync -type PI PI
add mapped point i_top_pix_href i_top_pix_href -type PI PI
add mapped point i_top_sda_in i_top_sda_in -type PI PI
add mapped point i_bram_doutb[11] i_bram_doutb[11] -type PI PI
add mapped point i_bram_doutb[10] i_bram_doutb[10] -type PI PI
add mapped point i_bram_doutb[9] i_bram_doutb[9] -type PI PI
add mapped point i_bram_doutb[8] i_bram_doutb[8] -type PI PI
add mapped point i_bram_doutb[7] i_bram_doutb[7] -type PI PI
add mapped point i_bram_doutb[6] i_bram_doutb[6] -type PI PI
add mapped point i_bram_doutb[5] i_bram_doutb[5] -type PI PI
add mapped point i_bram_doutb[4] i_bram_doutb[4] -type PI PI
add mapped point i_bram_doutb[3] i_bram_doutb[3] -type PI PI
add mapped point i_bram_doutb[2] i_bram_doutb[2] -type PI PI
add mapped point i_bram_doutb[1] i_bram_doutb[1] -type PI PI
add mapped point i_bram_doutb[0] i_bram_doutb[0] -type PI PI

//output ports
add mapped point o_top_cam_done o_top_cam_done -type PO PO
add mapped point o_top_reset o_top_reset -type PO PO
add mapped point o_top_pwdn o_top_pwdn -type PO PO
add mapped point o_top_xclk o_top_xclk -type PO PO
add mapped point o_top_sda_out o_top_sda_out -type PO PO
add mapped point o_top_sda_oe o_top_sda_oe -type PO PO
add mapped point o_top_sioc o_top_sioc -type PO PO
add mapped point o_top_vga_red[3] o_top_vga_red[3] -type PO PO
add mapped point o_top_vga_red[2] o_top_vga_red[2] -type PO PO
add mapped point o_top_vga_red[1] o_top_vga_red[1] -type PO PO
add mapped point o_top_vga_red[0] o_top_vga_red[0] -type PO PO
add mapped point o_top_vga_green[3] o_top_vga_green[3] -type PO PO
add mapped point o_top_vga_green[2] o_top_vga_green[2] -type PO PO
add mapped point o_top_vga_green[1] o_top_vga_green[1] -type PO PO
add mapped point o_top_vga_green[0] o_top_vga_green[0] -type PO PO
add mapped point o_top_vga_blue[3] o_top_vga_blue[3] -type PO PO
add mapped point o_top_vga_blue[2] o_top_vga_blue[2] -type PO PO
add mapped point o_top_vga_blue[1] o_top_vga_blue[1] -type PO PO
add mapped point o_top_vga_blue[0] o_top_vga_blue[0] -type PO PO
add mapped point o_top_vga_vsync o_top_vga_vsync -type PO PO
add mapped point o_top_vga_hsync o_top_vga_hsync -type PO PO
add mapped point o_bram_clka o_bram_clka -type PO PO
add mapped point o_bram_ena o_bram_ena -type PO PO
add mapped point o_bram_wea o_bram_wea -type PO PO
add mapped point o_bram_addra[18] o_bram_addra[18] -type PO PO
add mapped point o_bram_addra[17] o_bram_addra[17] -type PO PO
add mapped point o_bram_addra[16] o_bram_addra[16] -type PO PO
add mapped point o_bram_addra[15] o_bram_addra[15] -type PO PO
add mapped point o_bram_addra[14] o_bram_addra[14] -type PO PO
add mapped point o_bram_addra[13] o_bram_addra[13] -type PO PO
add mapped point o_bram_addra[12] o_bram_addra[12] -type PO PO
add mapped point o_bram_addra[11] o_bram_addra[11] -type PO PO
add mapped point o_bram_addra[10] o_bram_addra[10] -type PO PO
add mapped point o_bram_addra[9] o_bram_addra[9] -type PO PO
add mapped point o_bram_addra[8] o_bram_addra[8] -type PO PO
add mapped point o_bram_addra[7] o_bram_addra[7] -type PO PO
add mapped point o_bram_addra[6] o_bram_addra[6] -type PO PO
add mapped point o_bram_addra[5] o_bram_addra[5] -type PO PO
add mapped point o_bram_addra[4] o_bram_addra[4] -type PO PO
add mapped point o_bram_addra[3] o_bram_addra[3] -type PO PO
add mapped point o_bram_addra[2] o_bram_addra[2] -type PO PO
add mapped point o_bram_addra[1] o_bram_addra[1] -type PO PO
add mapped point o_bram_addra[0] o_bram_addra[0] -type PO PO
add mapped point o_bram_dina[11] o_bram_dina[11] -type PO PO
add mapped point o_bram_dina[10] o_bram_dina[10] -type PO PO
add mapped point o_bram_dina[9] o_bram_dina[9] -type PO PO
add mapped point o_bram_dina[8] o_bram_dina[8] -type PO PO
add mapped point o_bram_dina[7] o_bram_dina[7] -type PO PO
add mapped point o_bram_dina[6] o_bram_dina[6] -type PO PO
add mapped point o_bram_dina[5] o_bram_dina[5] -type PO PO
add mapped point o_bram_dina[4] o_bram_dina[4] -type PO PO
add mapped point o_bram_dina[3] o_bram_dina[3] -type PO PO
add mapped point o_bram_dina[2] o_bram_dina[2] -type PO PO
add mapped point o_bram_dina[1] o_bram_dina[1] -type PO PO
add mapped point o_bram_dina[0] o_bram_dina[0] -type PO PO
add mapped point o_bram_clkb o_bram_clkb -type PO PO
add mapped point o_bram_enb o_bram_enb -type PO PO
add mapped point o_bram_web o_bram_web -type PO PO
add mapped point o_bram_addrb[18] o_bram_addrb[18] -type PO PO
add mapped point o_bram_addrb[17] o_bram_addrb[17] -type PO PO
add mapped point o_bram_addrb[16] o_bram_addrb[16] -type PO PO
add mapped point o_bram_addrb[15] o_bram_addrb[15] -type PO PO
add mapped point o_bram_addrb[14] o_bram_addrb[14] -type PO PO
add mapped point o_bram_addrb[13] o_bram_addrb[13] -type PO PO
add mapped point o_bram_addrb[12] o_bram_addrb[12] -type PO PO
add mapped point o_bram_addrb[11] o_bram_addrb[11] -type PO PO
add mapped point o_bram_addrb[10] o_bram_addrb[10] -type PO PO
add mapped point o_bram_addrb[9] o_bram_addrb[9] -type PO PO
add mapped point o_bram_addrb[8] o_bram_addrb[8] -type PO PO
add mapped point o_bram_addrb[7] o_bram_addrb[7] -type PO PO
add mapped point o_bram_addrb[6] o_bram_addrb[6] -type PO PO
add mapped point o_bram_addrb[5] o_bram_addrb[5] -type PO PO
add mapped point o_bram_addrb[4] o_bram_addrb[4] -type PO PO
add mapped point o_bram_addrb[3] o_bram_addrb[3] -type PO PO
add mapped point o_bram_addrb[2] o_bram_addrb[2] -type PO PO
add mapped point o_bram_addrb[1] o_bram_addrb[1] -type PO PO
add mapped point o_bram_addrb[0] o_bram_addrb[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point OV7670_cam/cam_btn_start_db/counter[8]/q OV7670_cam/cam_btn_start_db/counter_reg[8]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[1]/q OV7670_cam/cam_btn_start_db/counter_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[2]/q OV7670_cam/cam_btn_start_db/counter_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[3]/q OV7670_cam/cam_btn_start_db/counter_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[6]/q OV7670_cam/cam_btn_start_db/counter_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[5]/q OV7670_cam/cam_btn_start_db/counter_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[7]/q OV7670_cam/cam_btn_start_db/counter_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[0]/q OV7670_cam/cam_btn_start_db/counter_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[4]/q OV7670_cam/cam_btn_start_db/counter_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[17]/q OV7670_cam/cam_btn_start_db/counter_reg[17]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[10]/q OV7670_cam/cam_btn_start_db/counter_reg[10]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[9]/q OV7670_cam/cam_btn_start_db/counter_reg[9]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[16]/q OV7670_cam/cam_btn_start_db/counter_reg[16]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[13]/q OV7670_cam/cam_btn_start_db/counter_reg[13]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[12]/q OV7670_cam/cam_btn_start_db/counter_reg[12]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[14]/q OV7670_cam/cam_btn_start_db/counter_reg[14]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[15]/q OV7670_cam/cam_btn_start_db/counter_reg[15]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/counter[11]/q OV7670_cam/cam_btn_start_db/counter_reg[11]/Q -type DFF DFF
add mapped point OV7670_cam/cam_btn_start_db/r_sample/q OV7670_cam/cam_btn_start_db/r_sample_reg/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/r2_vsync/q OV7670_cam/cam_pixels/r2_vsync_reg/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_wr/q OV7670_cam/cam_pixels/o_wr_reg/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/r1_vsync/q OV7670_cam/cam_pixels/r1_vsync_reg/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/pixel_data[3]/q OV7670_cam/cam_pixels/pixel_data_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/pixel_data[1]/q OV7670_cam/cam_pixels/pixel_data_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/pixel_data[0]/q OV7670_cam/cam_pixels/pixel_data_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/pixel_data[2]/q OV7670_cam/cam_pixels/pixel_data_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/SM_state[0]/q OV7670_cam/cam_pixels/SM_state_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/SM_state[1]/q OV7670_cam/cam_pixels/SM_state_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[1]/q OV7670_cam/cam_pixels/o_pix_data_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[7]/q OV7670_cam/cam_pixels/o_pix_addr_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[8]/q OV7670_cam/cam_pixels/o_pix_addr_reg[8]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[9]/q OV7670_cam/cam_pixels/o_pix_addr_reg[9]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[10]/q OV7670_cam/cam_pixels/o_pix_addr_reg[10]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[11]/q OV7670_cam/cam_pixels/o_pix_addr_reg[11]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[12]/q OV7670_cam/cam_pixels/o_pix_addr_reg[12]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[13]/q OV7670_cam/cam_pixels/o_pix_addr_reg[13]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[14]/q OV7670_cam/cam_pixels/o_pix_addr_reg[14]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[15]/q OV7670_cam/cam_pixels/o_pix_addr_reg[15]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[16]/q OV7670_cam/cam_pixels/o_pix_addr_reg[16]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[17]/q OV7670_cam/cam_pixels/o_pix_addr_reg[17]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[6]/q OV7670_cam/cam_pixels/o_pix_addr_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[18]/q OV7670_cam/cam_pixels/o_pix_addr_reg[18]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[0]/q OV7670_cam/cam_pixels/o_pix_data_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[0]/q OV7670_cam/cam_pixels/o_pix_addr_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[8]/q OV7670_cam/cam_pixels/o_pix_data_reg[8]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[4]/q OV7670_cam/cam_pixels/o_pix_data_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[5]/q OV7670_cam/cam_pixels/o_pix_data_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[2]/q OV7670_cam/cam_pixels/o_pix_addr_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[3]/q OV7670_cam/cam_pixels/o_pix_addr_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[6]/q OV7670_cam/cam_pixels/o_pix_data_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[7]/q OV7670_cam/cam_pixels/o_pix_data_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[3]/q OV7670_cam/cam_pixels/o_pix_data_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[4]/q OV7670_cam/cam_pixels/o_pix_addr_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[9]/q OV7670_cam/cam_pixels/o_pix_data_reg[9]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[5]/q OV7670_cam/cam_pixels/o_pix_addr_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[10]/q OV7670_cam/cam_pixels/o_pix_data_reg[10]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[11]/q OV7670_cam/cam_pixels/o_pix_data_reg[11]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_addr[1]/q OV7670_cam/cam_pixels/o_pix_addr_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/o_pix_data[2]/q OV7670_cam/cam_pixels/o_pix_data_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/cam_pixels/r_half_data/q OV7670_cam/cam_pixels/r_half_data_reg/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[0]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[1]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[3]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[4]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[5]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[6]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[7]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[8]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[8]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[9]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[9]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[10]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[10]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[11]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[11]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[12]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[12]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[13]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[13]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[14]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[14]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[15]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[15]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_Registers/o_dout[2]/q OV7670_cam/configure_cam/OV7670_Registers/o_dout_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/SM_state[0]/q OV7670_cam/configure_cam/OV7670_config/SM_state_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/SM_state[1]/q OV7670_cam/configure_cam/OV7670_config/SM_state_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_config_done/q OV7670_cam/configure_cam/OV7670_config/o_config_done_reg/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_start/q OV7670_cam/configure_cam/OV7670_config/o_i2c_start_reg/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_rom_addr[0]/q OV7670_cam/configure_cam/OV7670_config/o_rom_addr_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_rom_addr[1]/q OV7670_cam/configure_cam/OV7670_config/o_rom_addr_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_rom_addr[2]/q OV7670_cam/configure_cam/OV7670_config/o_rom_addr_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_rom_addr[3]/q OV7670_cam/configure_cam/OV7670_config/o_rom_addr_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_rom_addr[4]/q OV7670_cam/configure_cam/OV7670_config/o_rom_addr_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_rom_addr[5]/q OV7670_cam/configure_cam/OV7670_config/o_rom_addr_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_rom_addr[6]/q OV7670_cam/configure_cam/OV7670_config/o_rom_addr_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_rom_addr[7]/q OV7670_cam/configure_cam/OV7670_config/o_rom_addr_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[0]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[1]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[2]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[3]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[4]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[5]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[6]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[7]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[8]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[8]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[9]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[9]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[10]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[10]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[11]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[11]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[12]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[12]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[13]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[13]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[14]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[14]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[15]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[15]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[16]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[16]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[17]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[17]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[18]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[18]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/timer[19]/q OV7670_cam/configure_cam/OV7670_config/timer_reg[19]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_addr[3]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_addr_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_addr[0]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_addr_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_addr[1]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_addr_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_addr[2]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_addr_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/SM_return_state[0]/q OV7670_cam/configure_cam/OV7670_config/SM_return_state_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_addr[4]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_addr_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_addr[5]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_addr_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_addr[6]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_addr_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_data[7]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_data_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_data[0]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_data_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_data[1]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_data_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_data[2]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_data_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_data[3]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_data_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_data[4]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_data_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_data[5]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_data_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_data[6]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_data_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/OV7670_config/o_i2c_addr[7]/q OV7670_cam/configure_cam/OV7670_config/o_i2c_addr_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r2_en_sda/q OV7670_cam/configure_cam/SCCB_HERE/r2_en_sda_reg/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r2_scl/q OV7670_cam/configure_cam/SCCB_HERE/r2_scl_reg/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr[0]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr[1]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr[2]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr[3]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr[4]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr[5]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr[6]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr[7]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_addr_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_data[0]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_data_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_data[1]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_data_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_data[2]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_data_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_data[3]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_data_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_data[4]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_data_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_data[5]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_data_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_data[6]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_data_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_latched_data[7]/q OV7670_cam/configure_cam/SCCB_HERE/r_latched_data_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_ready/q OV7670_cam/configure_cam/SCCB_HERE/r_ready_reg/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_tx[0]/q OV7670_cam/configure_cam/SCCB_HERE/r_tx_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_tx[1]/q OV7670_cam/configure_cam/SCCB_HERE/r_tx_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_tx[2]/q OV7670_cam/configure_cam/SCCB_HERE/r_tx_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_tx[3]/q OV7670_cam/configure_cam/SCCB_HERE/r_tx_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_tx[4]/q OV7670_cam/configure_cam/SCCB_HERE/r_tx_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_tx[5]/q OV7670_cam/configure_cam/SCCB_HERE/r_tx_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_tx[6]/q OV7670_cam/configure_cam/SCCB_HERE/r_tx_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_tx[7]/q OV7670_cam/configure_cam/SCCB_HERE/r_tx_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_tx[8]/q OV7670_cam/configure_cam/SCCB_HERE/r_tx_reg[8]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_write/q OV7670_cam/configure_cam/SCCB_HERE/r_write_reg/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/data_state/q OV7670_cam/configure_cam/SCCB_HERE/data_state_reg/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_byte_index[0]/q OV7670_cam/configure_cam/SCCB_HERE/r_byte_index_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_byte_index[1]/q OV7670_cam/configure_cam/SCCB_HERE/r_byte_index_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index[0]/q OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index[1]/q OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index[2]/q OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index[3]/q OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index[4]/q OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index[5]/q OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index[6]/q OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index[7]/q OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index_reg[7]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index[8]/q OV7670_cam/configure_cam/SCCB_HERE/r_data_bit_index_reg[8]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_scl/q OV7670_cam/configure_cam/SCCB_HERE/r_scl_reg/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/r_sda/q OV7670_cam/configure_cam/SCCB_HERE/r_sda_reg/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/state[0]/q OV7670_cam/configure_cam/SCCB_HERE/state_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/state[1]/q OV7670_cam/configure_cam/SCCB_HERE/state_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/state[2]/q OV7670_cam/configure_cam/SCCB_HERE/state_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/state[3]/q OV7670_cam/configure_cam/SCCB_HERE/state_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/timer[0]/q OV7670_cam/configure_cam/SCCB_HERE/timer_reg[0]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/timer[1]/q OV7670_cam/configure_cam/SCCB_HERE/timer_reg[1]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/timer[2]/q OV7670_cam/configure_cam/SCCB_HERE/timer_reg[2]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/timer[3]/q OV7670_cam/configure_cam/SCCB_HERE/timer_reg[3]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/timer[4]/q OV7670_cam/configure_cam/SCCB_HERE/timer_reg[4]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/timer[5]/q OV7670_cam/configure_cam/SCCB_HERE/timer_reg[5]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/timer[6]/q OV7670_cam/configure_cam/SCCB_HERE/timer_reg[6]/Q -type DFF DFF
add mapped point OV7670_cam/configure_cam/SCCB_HERE/timer[7]/q OV7670_cam/configure_cam/SCCB_HERE/timer_reg[7]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/vc[9]/q display_interface/vga_timing_signals/vc_reg[9]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/vc[7]/q display_interface/vga_timing_signals/vc_reg[7]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/vc[8]/q display_interface/vga_timing_signals/vc_reg[8]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/vc[6]/q display_interface/vga_timing_signals/vc_reg[6]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/hc[9]/q display_interface/vga_timing_signals/hc_reg[9]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/vc[5]/q display_interface/vga_timing_signals/vc_reg[5]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/hc[8]/q display_interface/vga_timing_signals/hc_reg[8]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/vc[0]/q display_interface/vga_timing_signals/vc_reg[0]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/hc[7]/q display_interface/vga_timing_signals/hc_reg[7]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/vc[3]/q display_interface/vga_timing_signals/vc_reg[3]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/vc[2]/q display_interface/vga_timing_signals/vc_reg[2]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/vc[4]/q display_interface/vga_timing_signals/vc_reg[4]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/hc[5]/q display_interface/vga_timing_signals/hc_reg[5]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/hc[6]/q display_interface/vga_timing_signals/hc_reg[6]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/hc[3]/q display_interface/vga_timing_signals/hc_reg[3]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/hc[4]/q display_interface/vga_timing_signals/hc_reg[4]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/hc[2]/q display_interface/vga_timing_signals/hc_reg[2]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/vc[1]/q display_interface/vga_timing_signals/vc_reg[1]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/hc[1]/q display_interface/vga_timing_signals/hc_reg[1]/Q -type DFF DFF
add mapped point display_interface/vga_timing_signals/hc[0]/q display_interface/vga_timing_signals/hc_reg[0]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[5]/q display_interface/o_pix_addr_reg[5]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[7]/q display_interface/o_pix_addr_reg[7]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[6]/q display_interface/o_pix_addr_reg[6]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[2]/q display_interface/o_pix_addr_reg[2]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[3]/q display_interface/o_pix_addr_reg[3]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[4]/q display_interface/o_pix_addr_reg[4]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[1]/q display_interface/o_pix_addr_reg[1]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[0]/q display_interface/o_pix_addr_reg[0]/Q -type DFF DFF
add mapped point display_interface/r_SM_state[1]/q display_interface/r_SM_state_reg[1]/Q -type DFF DFF
add mapped point display_interface/r_SM_state[0]/q display_interface/r_SM_state_reg[0]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[13]/q display_interface/o_pix_addr_reg[13]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[9]/q display_interface/o_pix_addr_reg[9]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[10]/q display_interface/o_pix_addr_reg[10]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[11]/q display_interface/o_pix_addr_reg[11]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[12]/q display_interface/o_pix_addr_reg[12]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[8]/q display_interface/o_pix_addr_reg[8]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[14]/q display_interface/o_pix_addr_reg[14]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[15]/q display_interface/o_pix_addr_reg[15]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[16]/q display_interface/o_pix_addr_reg[16]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[17]/q display_interface/o_pix_addr_reg[17]/Q -type DFF DFF
add mapped point display_interface/o_pix_addr[18]/q display_interface/o_pix_addr_reg[18]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[11]/q pixel_memory/o_bram_data_reg[11]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[10]/q pixel_memory/o_bram_data_reg[10]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[8]/q pixel_memory/o_bram_data_reg[8]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[4]/q pixel_memory/o_bram_data_reg[4]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[3]/q pixel_memory/o_bram_data_reg[3]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[7]/q pixel_memory/o_bram_data_reg[7]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[2]/q pixel_memory/o_bram_data_reg[2]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[1]/q pixel_memory/o_bram_data_reg[1]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[9]/q pixel_memory/o_bram_data_reg[9]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[6]/q pixel_memory/o_bram_data_reg[6]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[0]/q pixel_memory/o_bram_data_reg[0]/Q -type DFF DFF
add mapped point pixel_memory/o_bram_data[5]/q pixel_memory/o_bram_data_reg[5]/Q -type DFF DFF
add mapped point top_btn_db/counter[9]/q top_btn_db/counter_reg[9]/Q -type DFF DFF
add mapped point top_btn_db/counter[2]/q top_btn_db/counter_reg[2]/Q -type DFF DFF
add mapped point top_btn_db/counter[3]/q top_btn_db/counter_reg[3]/Q -type DFF DFF
add mapped point top_btn_db/counter[4]/q top_btn_db/counter_reg[4]/Q -type DFF DFF
add mapped point top_btn_db/counter[5]/q top_btn_db/counter_reg[5]/Q -type DFF DFF
add mapped point top_btn_db/counter[6]/q top_btn_db/counter_reg[6]/Q -type DFF DFF
add mapped point top_btn_db/counter[8]/q top_btn_db/counter_reg[8]/Q -type DFF DFF
add mapped point top_btn_db/counter[0]/q top_btn_db/counter_reg[0]/Q -type DFF DFF
add mapped point top_btn_db/counter[7]/q top_btn_db/counter_reg[7]/Q -type DFF DFF
add mapped point top_btn_db/counter[1]/q top_btn_db/counter_reg[1]/Q -type DFF DFF
add mapped point top_btn_db/counter[11]/q top_btn_db/counter_reg[11]/Q -type DFF DFF
add mapped point top_btn_db/counter[10]/q top_btn_db/counter_reg[10]/Q -type DFF DFF
add mapped point top_btn_db/counter[17]/q top_btn_db/counter_reg[17]/Q -type DFF DFF
add mapped point top_btn_db/counter[16]/q top_btn_db/counter_reg[16]/Q -type DFF DFF
add mapped point top_btn_db/counter[13]/q top_btn_db/counter_reg[13]/Q -type DFF DFF
add mapped point top_btn_db/counter[14]/q top_btn_db/counter_reg[14]/Q -type DFF DFF
add mapped point top_btn_db/counter[15]/q top_btn_db/counter_reg[15]/Q -type DFF DFF
add mapped point top_btn_db/counter[12]/q top_btn_db/counter_reg[12]/Q -type DFF DFF
add mapped point top_btn_db/r_sample/q top_btn_db/r_sample_reg/Q -type DFF DFF
add mapped point r2_rstn_clk25m/q r2_rstn_clk25m_reg/Q -type DFF DFF
add mapped point r2_rstn_top_clk/q r2_rstn_top_clk_reg/Q -type DFF DFF
add mapped point r2_rstn_pclk/q r2_rstn_pclk_reg/Q -type DFF DFF
add mapped point r1_rstn_clk25m/q r1_rstn_clk25m_reg/Q -type DFF DFF
add mapped point r1_rstn_top_clk/q r1_rstn_top_clk_reg/Q -type DFF DFF
add mapped point r1_rstn_pclk/q r1_rstn_pclk_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
